version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/consbio/csrt.git
      - (cd csrt && git submodule init)
      - (cd csrt/javascript && npm install)
  build:
    commands:
      - (cd csrt/javascript && npm run-script build)

artifacts:
  files: "csrt/**/*"
